# prediction parameters

bu_key : 16
bu_code : 'MFR'
model_label : '202202_to_202301_model'
run_type : 'ONE-OFF'
current_month_flag : 0
specified_start_month : 202302
specified_end_month : 202401
output_table_name : 'mfr_high_skincare_model_output'